name: 01 - Building blocks

on: push
  
jobs:
     echo-Hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "hello world!"
     echo-goodbye:
          runs-on: ubuntu-latest
          steps:
              - name: Successful step
                run:  |
                  echo  "You will succed"
                  exit 0
              - name: Say goodbye
                run: echo "Goodbye!"
